global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins'
    metrics_path: '/prometheus/'
    static_configs:
      - targets: ['jenkins-server:8080']
    basic_auth:
      username: 'jubeth'  # Ensure this is your actual Jenkins username!
      password: 'fd5c570339a2c148877988c51bd4230b' # <--- Paste your token here